/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
	],
  safelist: [
    'bg-doctor',
    'bg-doctor-light',
    'bg-doctor-dark',
    'text-doctor',
    'text-doctor-light',
    'text-doctor-dark',
    'border-doctor',
    'border-doctor-light',
    'border-doctor-dark',
    'hover:bg-doctor-dark',
    'bg-patient',
    'bg-patient-light',
    'bg-patient-dark',
    'text-patient',
    'border-patient',
    'bg-pharmacy',
    'bg-pharmacy-light',
    'bg-pharmacy-dark',
    'text-pharmacy',
    'border-pharmacy',
    'bg-admin',
    'bg-admin-light',
    'bg-admin-dark',
    'text-admin',
    'border-admin'
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Medical platform specific colors
        patient: {
          DEFAULT: "#3B82F6", // Blue
          light: "#DBEAFE",
          dark: "#1E40AF",
        },
        "patient-light": "#DBEAFE",
        "patient-dark": "#1E40AF",
        doctor: {
          DEFAULT: "#10B981", // Green
          light: "#D1FAE5",
          dark: "#047857",
        },
        "doctor-light": "#D1FAE5",
        "doctor-dark": "#047857",
        pharmacy: {
          DEFAULT: "#F59E0B", // Orange
          light: "#FEF3C7",
          dark: "#D97706",
        },
        "pharmacy-light": "#FEF3C7",
        "pharmacy-dark": "#D97706",
        admin: {
          DEFAULT: "#8B5CF6", // Purple
          light: "#EDE9FE",
          dark: "#7C3AED",
        },
        "admin-light": "#EDE9FE",
        "admin-dark": "#7C3AED",
        // ── Stitch "Serene Healthcare Identity" design tokens ──────────────
        // primary / secondary / background reuse the existing CSS-var-backed
        // tokens and are re-themed only inside the `.stitch-theme` scope
        // (see globals.css). Everything below is additive and collision-free.
        surface: "#ecfdfb",
        "surface-dim": "#ccdddb",
        "surface-bright": "#ecfdfb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#e6f7f5",
        "surface-container": "#e0f1ef",
        "surface-container-high": "#dbecea",
        "surface-container-highest": "#d5e6e4",
        "surface-variant": "#d5e6e4",
        "surface-tint": "#006b5f",
        "on-surface": "#0f1e1d",
        "on-surface-variant": "#3e4946",
        "inverse-surface": "#243332",
        "inverse-on-surface": "#e3f4f2",
        outline: "#6e7976",
        "outline-variant": "#bec9c5",
        "primary-container": "#1f7a6e",
        "on-primary": "#ffffff",
        "on-primary-container": "#b3fff1",
        "inverse-primary": "#83d5c7",
        "primary-fixed": "#9ff2e3",
        "primary-fixed-dim": "#83d5c7",
        "on-primary-fixed": "#00201c",
        "on-primary-fixed-variant": "#005047",
        "secondary-container": "#fd7958",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6e1500",
        "secondary-fixed": "#ffdad2",
        "secondary-fixed-dim": "#ffb4a2",
        "on-secondary-fixed": "#3c0700",
        "on-secondary-fixed-variant": "#862208",
        tertiary: "#006231",
        "tertiary-container": "#007e40",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#c1ffcc",
        "tertiary-fixed": "#7efba4",
        "tertiary-fixed-dim": "#61de8a",
        "on-tertiary-fixed": "#00210c",
        "on-tertiary-fixed-variant": "#005228",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "accent-coral": "#FF7A59",
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        "section-gap": "40px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "container-margin": "20px",
      },
      fontFamily: {
        jakarta: ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "headline-sm-mobile": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "label-md": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-md": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["30px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-sm-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "fade-in": {
          "0%": { opacity: 0, transform: "translateY(10px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        "slide-in": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}